package org.agmas.harpymodloader;

import io.wifi.starrailexpress.api.GameMode;
import io.wifi.starrailexpress.api.SREGameModes;
import io.wifi.starrailexpress.api.SRERole;
import io.wifi.starrailexpress.api.TMMRoles;
import io.wifi.starrailexpress.client.gui.RoleAnnouncementTexts;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.command.v2.ArgumentTypeRegistry;
import net.fabricmc.fabric.api.command.v2.CommandRegistrationCallback;
import net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents;
import net.minecraft.commands.synchronization.SingletonArgumentInfo;
import net.minecraft.network.chat.MutableComponent;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.entity.player.Player;
import org.agmas.harpymodloader.commands.*;
import org.agmas.harpymodloader.commands.argument.ModifierArgumentType;
import org.agmas.harpymodloader.commands.argument.RoleArgumentType;
import org.agmas.harpymodloader.modded_murder.ModdedWeights;
import org.agmas.harpymodloader.modifiers.HMLModifiers;
import org.agmas.harpymodloader.modifiers.SREModifier;
import org.agmas.noellesroles.utils.RoleUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.UUID;

public class Harpymodloader implements ModInitializer {
    /**
     * 支持正版，从你我做起
     * 此选项用于皮肤模组，避免私人的皮肤模组（枪、球棒等）被拿去盈利。
     * 如果您遇到相关问题，去掉皮肤模组（枪、球棒等）即可。
     */
    public static boolean officialVerify = true;
    /**
     * 职业对应关系映射
     * 支持同时分配两个关联职业（例如医生+毒师）
     * Key: 主职业, Value: 关联职业
     */
    // public static HashMap<SRERole, SRERole> Occupations_Roles = new HashMap<>();

    public static HashMap<ResourceLocation, Integer> ROLE_MAX = new HashMap<>();
    /**
     * 最大修饰符数量，-2为无限制
     */
    public static HashMap<ResourceLocation, Integer> MODIFIER_MAX = new HashMap<>();

    public static HashMap<SRERole, List<UUID>> FORCED_MODDED_ROLE = new HashMap<>();
    public static HashMap<UUID, SRERole> FORCED_MODDED_ROLE_FLIP = new HashMap<>();

    public static HashMap<SREModifier, List<UUID>> FORCED_MODDED_MODIFIER = new HashMap<>();

    public static ArrayList<SRERole> VANNILA_ROLES = new ArrayList<>();
    public static ArrayList<SRERole> SPECIAL_ROLES = new ArrayList<>();
    public static ArrayList<SRERole> OVERWRITE_ROLES = new ArrayList<>();
    public static String MOD_ID = "harpymodloader";

    public static GameMode MODDED_GAMEMODE;
    public static boolean wantsToStartVannila = false;

    public static HashMap<SRERole, RoleAnnouncementTexts.RoleAnnouncementText> autogeneratedAnnouncements = new HashMap<>();
    public static HashMap<RoleAnnouncementTexts.RoleAnnouncementText, SRERole> roleAnnouncements = new HashMap<>();

    public static final Logger LOGGER = LoggerFactory.getLogger("HarpyModLoader");

    @Override
    public void onInitialize() {
        VANNILA_ROLES.add(TMMRoles.LOOSE_END);
        VANNILA_ROLES.add(TMMRoles.CIVILIAN);
        VANNILA_ROLES.add(TMMRoles.KILLER);
        VANNILA_ROLES.add(TMMRoles.VIGILANTE);
        VANNILA_ROLES.add(TMMRoles.DISCOVERY_CIVILIAN);

        SPECIAL_ROLES.add(TMMRoles.LOOSE_END);
        SPECIAL_ROLES.add(TMMRoles.DISCOVERY_CIVILIAN);
        SPECIAL_ROLES.add(TMMRoles.CIVILIAN); // civilian is considered special since it can't be assigned, just given
                                              // out to everyone

        OVERWRITE_ROLES.add(TMMRoles.CIVILIAN);
        OVERWRITE_ROLES.add(TMMRoles.KILLER);

        ModdedWeights.init();

        registerCommands();
        HMLModifiers.init();

        MODDED_GAMEMODE = SREGameModes.MURDER;

        ServerLifecycleEvents.SERVER_STARTED.register((minecraftServer -> {
            refreshRoles();
        }));
    }

    public static void refreshRoles() {
        for (SRERole role : TMMRoles.ROLES.values()) {
            if (SPECIAL_ROLES.contains(role))
                continue;
            if (!ModdedWeights.roleRounds.containsKey(role)) {
                ModdedWeights.roleRounds.put(role, new HashMap<>());
                RoleAnnouncementTexts.RoleAnnouncementText roleAnnouncementText = new RoleAnnouncementTexts.RoleAnnouncementText(
                        role.identifier(), role.color());
                autogeneratedAnnouncements.put(role, roleAnnouncementText);
                roleAnnouncements.put(roleAnnouncementText, role);
                RoleAnnouncementTexts.registerRoleAnnouncementText(role.identifier(), roleAnnouncementText);
            }
        }
    }

    public static void addToForcedModifiers(SREModifier modifier, Player player) {
        if (!FORCED_MODDED_MODIFIER.containsKey(modifier))
            FORCED_MODDED_MODIFIER.put(modifier, new ArrayList<>());
        FORCED_MODDED_MODIFIER.get(modifier).add(player.getUUID());
    }

    public static void addToForcedRoles(SRERole role, Player player) {
        if (!FORCED_MODDED_ROLE.containsKey(role))
            FORCED_MODDED_ROLE.put(role, new ArrayList<>());
        FORCED_MODDED_ROLE.get(role).add(player.getUUID());
        FORCED_MODDED_ROLE_FLIP.put(player.getUUID(), role);
    }

    public static void setRoleMaximum(ResourceLocation role, Integer max) {
        ROLE_MAX.put(role, max);
    }

    public static void setRoleMaximum(SRERole role, Integer max) {
        setRoleMaximum(role.identifier(), max);
    }

    public void registerCommands() {
        ArgumentTypeRegistry.registerArgumentType(
                ResourceLocation.fromNamespaceAndPath(MOD_ID, "role"),
                RoleArgumentType.class,
                new RoleArgumentType.Serializer());
        ArgumentTypeRegistry.registerArgumentType(
                ResourceLocation.fromNamespaceAndPath(MOD_ID, "modifier"),
                ModifierArgumentType.class,
                SingletonArgumentInfo.contextFree(ModifierArgumentType::create));

        CommandRegistrationCallback.EVENT.register((dispatcher, registryAccess, environment) -> {
            ForceRoleCommand.register(dispatcher);
            SetEnabledRoleCommand.register(dispatcher);
            ListRolesCommand.register(dispatcher);
            ForceModifierCommand.register(dispatcher);
            SetEnabledModifierCommand.register(dispatcher);
            RoleCountManager.registerCommands(dispatcher);
            SetRoleWeightCommand.register(dispatcher);
            SetPlayerWeightCommand.register(dispatcher);
            ToggleCustomRoleWeightsCommand.register(dispatcher);
            ChangeRoleCommand.register(dispatcher);
            ClassChangeTestCommand.register(dispatcher);
            ChangeModifierCommand.register(dispatcher);
            SetOccupationRoleCommand.register(dispatcher);
        });
    }

    public static MutableComponent getRoleName(SRERole role) {
        return RoleUtils.getRoleName(role);
    }

    /**
     * 添加职业对应关系（即同时分配两个职业）
     * 例如：setOccupationRole(医生, 毒师) 表示分配医生时也会分配毒师
     * 
     * @param mainRole      主职业
     * @param companionRole 关联职业
     */
    public static void addOccupationRole(SRERole mainRole, SRERole companionRole) {
        mainRole.addOccupationRoleOnce(companionRole);
        LOGGER.debug("Added occupation relation: " + mainRole.getIdentifier() + " -> " + companionRole.getIdentifier());
    }

    /**
     * 移除职业对应关系
     * 
     * @param mainRole      要移除对应关系的职业
     * @param companionRole 要移除对应关系的职业
     */
    public static void clearOccupationRole(SRERole mainRole, SRERole companionRole) {
        mainRole.removeOccupationRole(mainRole, companionRole);
        LOGGER.debug("Removed occupation relation for: " + mainRole.getIdentifier());
    }

    /**
     * 清空职业对应关系
     * 
     * @param mainRole 要移除对应关系的职业
     */
    public static void clearOccupationRole(SRERole mainRole) {
        mainRole.clearOccupationRole();
        LOGGER.debug("Cleared occupation relation for: " + mainRole.getIdentifier());
    }


    /**
     * 获取职业的关联职业
     * 
     * @param role 主职业
     * @return 关联职业，如果没有则返回null
     */
    public static ArrayList<SRERole> getOccupationRoles(SRERole role) {
        return role.getoccupationRoles();
    }

    /**
     * 检查职业是否有关联职业
     */
    public static boolean hasOccupationRole(SRERole role) {
        return role.hasOccupationRole();
    }
}